// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EncrypterClient is the client API for Encrypter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EncrypterClient interface {
	Encrypt(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	Decrypt(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type encrypterClient struct {
	cc grpc.ClientConnInterface
}

func NewEncrypterClient(cc grpc.ClientConnInterface) EncrypterClient {
	return &encrypterClient{cc}
}

func (c *encrypterClient) Encrypt(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/Encrypter/Encrypt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *encrypterClient) Decrypt(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/Encrypter/Decrypt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EncrypterServer is the server API for Encrypter service.
// All implementations must embed UnimplementedEncrypterServer
// for forward compatibility
type EncrypterServer interface {
	Encrypt(context.Context, *Request) (*Response, error)
	Decrypt(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedEncrypterServer()
}

// UnimplementedEncrypterServer must be embedded to have forward compatible implementations.
type UnimplementedEncrypterServer struct {
}

func (UnimplementedEncrypterServer) Encrypt(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Encrypt not implemented")
}
func (UnimplementedEncrypterServer) Decrypt(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Decrypt not implemented")
}
func (UnimplementedEncrypterServer) mustEmbedUnimplementedEncrypterServer() {}

// UnsafeEncrypterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EncrypterServer will
// result in compilation errors.
type UnsafeEncrypterServer interface {
	mustEmbedUnimplementedEncrypterServer()
}

func RegisterEncrypterServer(s grpc.ServiceRegistrar, srv EncrypterServer) {
	s.RegisterService(&Encrypter_ServiceDesc, srv)
}

func _Encrypter_Encrypt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EncrypterServer).Encrypt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Encrypter/Encrypt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EncrypterServer).Encrypt(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Encrypter_Decrypt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EncrypterServer).Decrypt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Encrypter/Decrypt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EncrypterServer).Decrypt(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Encrypter_ServiceDesc is the grpc.ServiceDesc for Encrypter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Encrypter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Encrypter",
	HandlerType: (*EncrypterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Encrypt",
			Handler:    _Encrypter_Encrypt_Handler,
		},
		{
			MethodName: "Decrypt",
			Handler:    _Encrypter_Decrypt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/encryption.proto",
}
